version: "3"
services:
  frontend:
    image: xmemefrontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - "xmemeapp"
  backend:
    image: xmemebackend
    ports:
      - "5000:5000"
    networks:
      - xmemeapp
networks:
  xmemeapp:
    driver: bridge 

volumes:
  mongo-data:
    driver: local